
author = "Ghassan Karwchan"
description = "Ghassan Karwchan Blog"
keywords = "blog,developer,personal"
img_home = "img/home-bg.jpg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/home-bg.jpg"
bio = "a personal website"

[social]
#twitter = "johndoe"
#facebook = "johndoe"
#zhihu = "johndoe"
#weibo = "johndoe"
github = "gkarwchan"
# gitlab = "johndoe"
linkedin = "ghassankarwchan"
rss = true


# See https://giscus.app/
[giscus]
enable = true
repo = "gkarwchan/hugoblog"
repo_id = "R_kgDOI9C7aQ"
category = "General"
category_id = "DIC_kwDOI9C7ac4CUTNT"
input_position = "top"
theme = "light_tritanopia"
lang = "en"
mapping = "pathname"
strict = "0"
reactions-enabled = "1"
emit-metadata = "0"
input-position = "bottom"
